# Generated by Django 2.2.1 on 2019-05-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_priority',
            name='results',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_priority', to='compass.Results'),
        ),
    ]
