# Generated by Django 2.0.4 on 2018-04-12 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0002_auto_20180411_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmb',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rmb', to='compass.Quiz'),
        ),
    ]
