# Generated by Django 2.0.4 on 2018-04-15 09:56

from django.db import migrations, models


def add_categories_to_questions(apps, schema_editor):
    Question = apps.get_model('compass', 'Question')
    question_categories = [
        {"What is state of data quality within your organisation?": "Data Quality"},
        {"How is cat modeling implemented in your organisation?": "Cat Modeling"},
        {"How do you approach non modelled risks?": "Non-Modelled"},
        {"Which criteria do you use for profiling submissions?": "Profiling Sumbissions"},
        {"What is your company’s approach to pricing?": "Pricing"},
        {"What procedures are in place for post bind data?": "Binding"},
        {"How to you manage your capacity?": "Capacity Management"},
        {"How would you best describe your approach to outwards risk transfer?": "Risk Transfer"},
        {"What are your procedures like during event response?": "Event Response"},
        {"What sort of reporting infrastructure do you have in place?": "Reporting"}
    ]
    for question_category in question_categories:
        q = Question.objects.get(description=list(question_category.keys())[0])
        q.category = list(question_category.values())[0]
        q.save()


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0003_rmb_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.RunPython(add_categories_to_questions)
    ]
