# Generated by Django 2.1.7 on 2019-04-17 10:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0004_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Result Answers',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('answers', models.ManyToManyField(related_name='results', to='compass.Result_Answer')),
            ],
            options={
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'User Details',
            },
        ),
        migrations.RemoveField(
            model_name='rmb',
            name='quiz',
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quiz'},
        ),
        migrations.AddField(
            model_name='answer',
            name='recommendation',
            field=models.TextField(default='Contact Anish Patel for more information'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.TextField(default='Exceedance', max_length=100),
        ),
        migrations.DeleteModel(
            name='RMB',
        ),
        migrations.AddField(
            model_name='results',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizresults', to='compass.Quiz'),
        ),
        migrations.AddField(
            model_name='results',
            name='userdetails',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compass.UserDetails'),
        ),
        migrations.AddField(
            model_name='result_answer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_answers', to='compass.Answer'),
        ),
        migrations.AddField(
            model_name='result_answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results_answers', to='compass.Question'),
        ),
    ]
