# Generated by Django 2.0.4 on 2018-04-15 10:49

from django.db import migrations


def add_recommendations_to_answers(apps, schema_editor):
    Answer = apps.get_model('compass', 'Answer')
    answers = Answer.objects.all()
    for answer in answers:
        answer.recommendation = "Contact Anish Patel for further details"
        answer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0005_answer_recommendation'),
    ]

    operations = [
        migrations.RunPython(add_recommendations_to_answers)
    ]
