# Generated by Django 2.0.4 on 2018-04-11 11:25

from django.db import migrations


def import_questions(apps, schema_editor):
    Quiz = apps.get_model('compass', 'Quiz')
    quiz_ = Quiz.objects.create()
    Question = apps.get_model('compass', 'Question')
    Answer = apps.get_model('compass', 'Answer')
    q = Question.objects.create(description="What is state of data quality within your organisation?", quiz=quiz_)
    Answer.objects.create(description="Data quality is integral throughout your entire organisation", score=5, question=q)
    Answer.objects.create(description="Data quality checks and scores at point of underwriting", score=3, question=q)
    Answer.objects.create(description="We are implementing more data quality checks through our organisation", score=2, question=q)
    Answer.objects.create(description="Our business functions without a consistent approach to data quality", score=1, question=q)

    q = Question.objects.create(description="How is cat modeling implemented in your organisation?", quiz=quiz_)
    Answer.objects.create(description="We have a fully automated, auditable cat modeling process integrated with our other systems", score=5, question=q)
    Answer.objects.create(description="We run cat models for a selection of submissions", score=2, question=q)
    Answer.objects.create(description="We validate the cat models that we use and have confidence in their output", score=3, question=q)
    Answer.objects.create(description="We do not run our own cat models, instead relying on broker results", score=1, question=q)

    q = Question.objects.create(description="How do you approach non modelled risks?", quiz=quiz_)
    Answer.objects.create(description="We manage our exposures using TIV split geographically", score=1, question=q)
    Answer.objects.create(description="At the point of underwriting we calculate a risk score based on different hazard layers", score=2, question=q)
    Answer.objects.create(description="We have internally developed models to help us better understand the risks alongside exposure accumulation", score=5, question=q)
    Answer.objects.create(description="Exposed limit is a key metric we use when evaluating submissions", score=3, question=q)

    q = Question.objects.create(description="Which criteria do you use for profiling submissions?", quiz=quiz_)
    Answer.objects.create(description="We use exposure and loss data from the submission in conjunction with historical data to provide a holistic view", score=4, question=q)
    Answer.objects.create(description="We have a view of our live capacity and use this alongside exposure and loss data for the submission to evaluate submissions", score=5, question=q)
    Answer.objects.create(description="We have some underwriting guidelines in place to control the types of risks that we take on but don’t have a live view of the group position", score=2, question=q)
    Answer.objects.create(description="We score the submissions that we receive using some exposure attributes", score=1, question=q)

    q = Question.objects.create(description="What is your company’s approach to pricing?", quiz=quiz_)
    Answer.objects.create(description="We use a combination of various exposure (TIV, EL) and loss metrics (AAL, CV, EP, TCE) along with marginal impact and non modelled factors to feed a pricing model", score=5, question=q)
    Answer.objects.create(description="We have a pricing model based on a combination of expected loss and a risk load of standard deviation", score=3, question=q)
    Answer.objects.create(description="The way we price our submissions differs from time to time and it is difficult to provide a breakdown of how prices were quoted historically", score=1, question=q)
    Answer.objects.create(description="We are unable to model all submissions pre-bind and price them based on the historical prices and use broker guidance", score=2, question=q)

    q = Question.objects.create(description="What procedures are in place for post bind data?", quiz=quiz_)
    Answer.objects.create(description="Our systems are often out of sync in terms of the participations across various lines post-bind", score=1, question=q)
    Answer.objects.create(description="We have a straight through processing system that takes the participations, re-runs any analytics and propagates through to all downstream systems", score=5, question=q)
    Answer.objects.create(description="We have a system of record and reconcile against it in all other systems and then manually update those other systems", score=3, question=q)
    Answer.objects.create(description="We fix our numbers manually across systems at fixed points in the year to ensure they are consistent", score=2, question=q)

    q = Question.objects.create(description="How to you manage your capacity?", quiz=quiz_)
    Answer.objects.create(description="We are able to understand our group wide positions and analyse the individual risk contributions to this position in real time with a view to portfolio optimisation", score=5, question=q)
    Answer.objects.create(description="We roll up our reinsurance book on a regular basis (monthly?)", score=3, question=q)
    Answer.objects.create(description="Rolling up our reinsurance book is a smooth, auditable process that has little manual intervention", score=4, question=q)
    Answer.objects.create(description="Rolling up our reinsurance book is time consuming and error prone and not performed very often", score=1, question=q)

    q = Question.objects.create(description="How would you best describe your approach to outwards risk transfer?", quiz=quiz_)
    Answer.objects.create(description="Brokers model our outwards reinsurance", score=1, question=q)
    Answer.objects.create(description="We roll up and model different risk transfer structures and triggers to optimise our outwards reinsurance purchasing", score=5, question=q)
    Answer.objects.create(description="When outwards reinsurance is applied, it informs our roll up process", score=3, question=q)
    Answer.objects.create(description="We have documented risk tolerance and risk appetite targets that we try to achieve", score=2, question=q)

    q = Question.objects.create(description="What are your procedures like during event response?", quiz=quiz_)
    Answer.objects.create(description="When major events are happening, we are able to understand our exposure and potential losses to an event near real time in order to take action", score=5, question=q)
    Answer.objects.create(description="We struggle to understand our potential losses to major events", score=1, question=q)
    Answer.objects.create(description="We regularly test our event response process to ensure that we are able to respond to it in the best way for the business", score=4, question=q)
    Answer.objects.create(description="We rely on brokers or industry loss estimates to provide us with loss estimates", score=2, question=q)

    q = Question.objects.create(description="What sort of reporting infrastructure do you have in place?", quiz=quiz_)
    Answer.objects.create(description="We have live dashboards for our exposure and cat losses across the business that those with sufficient privileges can view self-service", score=5, question=q)
    Answer.objects.create(description="We have an auditable reporting process that can produce management reports when needed", score=4, question=q)
    Answer.objects.create(description="We manually collate data in order to build reports on an ad-hoc basis", score=1, question=q)
    Answer.objects.create(description="We have automated processes to produce regulatory reports", score=3, question=q)


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0005_answer'),
    ]

    operations = [
        migrations.RunPython(import_questions)
    ]
