# Generated by Django 2.0.4 on 2018-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0006_ImportQuestionData'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmb',
            name='answer_list',
            field=models.TextField(default='{}'),
        ),
    ]
