# Generated by Django 2.1.7 on 2019-04-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0006_auto_20190417_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_answer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_answers', to='compass.Answer'),
        ),
        migrations.AlterField(
            model_name='result_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_answers', to='compass.Question'),
        ),
    ]
