# Generated by Django 2.1.7 on 2019-04-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0007_auto_20190417_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_answers', to='compass.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_answers', to='compass.Question')),
                ('question_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_answers', to='compass.Results')),
            ],
            options={
                'verbose_name_plural': 'Result Answers',
            },
        ),
        migrations.RemoveField(
            model_name='result_answer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='result_answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='result_answer',
            name='result_answer',
        ),
        migrations.DeleteModel(
            name='Result_Answer',
        ),
    ]
