# Generated by Django 2.1.7 on 2019-04-24 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0007_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_answers', to='compass.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_answers', to='compass.Question')),
            ],
            options={
                'verbose_name_plural': 'Result Answers',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.RemoveField(
            model_name='rmb',
            name='quiz',
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quiz'},
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': 'User Details'},
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='rmb',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sector',
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.TextField(default='Exceedance', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='RMB',
        ),
        migrations.AddField(
            model_name='results',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizresults', to='compass.Quiz'),
        ),
        migrations.AddField(
            model_name='results',
            name='userdetails',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compass.UserDetails'),
        ),
        migrations.AddField(
            model_name='question_choice',
            name='question_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_answers', to='compass.Results'),
        ),
    ]
