# Generated by Django 2.1.7 on 2019-04-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0008_auto_20190417_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='sector',
        ),
    ]
