# Generated by Django 2.1.7 on 2019-04-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0008_auto_20190424_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_quality', models.CharField(max_length=50)),
                ('cat_modeling', models.CharField(max_length=50)),
                ('non_modelled', models.CharField(max_length=50)),
                ('profiling_submissions', models.CharField(max_length=50)),
                ('results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_priority', to='compass.Results')),
            ],
        ),
    ]
