# Generated by Django 2.1.7 on 2019-04-24 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0009_business_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business_priority',
            options={'verbose_name_plural': 'Business Priorities'},
        ),
        migrations.AlterField(
            model_name='business_priority',
            name='results',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_priority', to='compass.Results'),
        ),
    ]
